################################################################################
## Copyright (c) 2014-2021, Lawrence Livermore National Security, LLC.
## Produced at the Lawrence Livermore National Laboratory.
## Written by the LBANN Research Team (B. Van Essen, et al.) listed in
## the CONTRIBUTORS file. <lbann-dev@llnl.gov>
##
## LLNL-CODE-697807.
## All rights reserved.
##
## This file is part of LBANN: Livermore Big Artificial Neural Network
## Toolkit. For details, see http://software.llnl.gov/LBANN or
## https://github.com/LLNL/LBANN.
##
## Licensed under the Apache License, Version 2.0 (the "Licensee"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at:
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
## implied. See the License for the specific language governing
## permissions and limitations under the license.
################################################################################

# Note: This configuration is specifically for LLNL compute
# clusters. To run testing locally, consult the README in the ci_test
# directory.

stages:
  - run-all-clusters

catalyst testing:
  stage: run-all-clusters
  trigger:
    strategy: depend
    include: .gitlab/catalyst/pipeline.yml

# corona testing:
#   stage: run-all-clusters
#   trigger:
#     strategy: depend
#     include: .gitlab/corona/pipeline.yml

lassen testing:
  stage: run-all-clusters
  trigger:
    strategy: depend
    include: .gitlab/lassen/pipeline.yml

pascal testing:
  stage: run-all-clusters
  trigger:
    strategy: depend
    include: .gitlab/pascal/pipeline.yml

ray testing:
  stage: run-all-clusters
  trigger:
    strategy: depend
    include: .gitlab/ray/pipeline.yml
